spring.application.name=pulsepass

# Flyway y Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar ejecuciones automaticas de esquemas SQL clásicos
spring.sql.init.mode=never
